### ISSUE TITLE
no body run this first?

### ISSUE THREAD

**Issue by ipconfiger** [sgrif/diesel_demo#1]
~/workspace/cloned/diesel_demo> cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
no matching package named `diesel` found (required by `diesel_demo`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.5.0
versions found: 0.4.1, 0.4.0, 0.3.0, ...

**Comment by sgrif** [comment]
This was written _in preparation for_ the 0.5.0 release. 0.5.0 is now on crates.io
