### ISSUE TITLE
Having trouble getting this to work

### ISSUE THREAD

**Issue by caldwell** [sgrif/diesel_demo#2]
I'm getting errors trying to compile this:

```
$ rustc --version
rustc 1.8.0-nightly (f50fb159e 2016-02-07)
$ cargo --version
cargo 0.9.0 (3e285ce 2016-02-05)
$ cargo build
   Compiling regex-syntax v0.2.2
   Compiling diesel_codegen v0.5.0
   Compiling libc v0.2.6
   Compiling byteorder v0.3.13
   Compiling pq-sys v0.2.1
   Compiling memchr v0.1.7
   Compiling diesel v0.5.0
   Compiling aho-corasick v0.4.1
   Compiling regex v0.1.48
   Compiling dotenv v0.8.0
   Compiling dotenv_codegen v0.8.0
   Compiling dotenv_macros v0.8.0
   Compiling diesel_demo v0.1.0 (file:///path/to/diesel_demo-git)
src/lib.rs:1:1: 41:1 error: Expected a struct or tuple struct for `#[insertable_into]`
src/lib.rs: 1 #![cfg_attr(feature = "nightly", feature(custom_derive, custom_attribute, plugin))]
src/lib.rs: 2 #![cfg_attr(feature = "nightly", plugin(diesel_codegen, dotenv_macros))]
src/lib.rs: 3
src/lib.rs: 4 #[macro_use]
src/lib.rs: 5 extern crate diesel;
src/lib.rs: 6 extern crate dotenv;
              ...
src/lib.rs:1:1: 41:1 error: Expected a struct or tuple struct for `#[insertable_into]`
src/lib.rs: 1 #![cfg_attr(feature = "nightly", feature(custom_derive, custom_attribute, plugin))]
src/lib.rs: 2 #![cfg_attr(feature = "nightly", plugin(diesel_codegen, dotenv_macros))]
src/lib.rs: 3
src/lib.rs: 4 #[macro_use]
src/lib.rs: 5 extern crate diesel;
src/lib.rs: 6 extern crate dotenv;
              ...
src/lib.rs:1:1: 41:1 error: Expected a struct or tuple struct for `#[insertable_into]`
src/lib.rs: 1 #![cfg_attr(feature = "nightly", feature(custom_derive, custom_attribute, plugin))]
src/lib.rs: 2 #![cfg_attr(feature = "nightly", plugin(diesel_codegen, dotenv_macros))]
src/lib.rs: 3
src/lib.rs: 4 #[macro_use]
src/lib.rs: 5 extern crate diesel;
src/lib.rs: 6 extern crate dotenv;
              ...
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'index out of bounds: the len is 66 but the index is 87', src/libcollections/vec.rs:1134
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Could not compile `diesel_demo`.

To learn more, run the command again with --verbose.
```

Any ideas? I'd love to try it out!

**Comment by sgrif** [comment]
Sorry, without more details there's not much I can do to help. I've not been able to replicate the problems you've described.

**Comment by caldwell** [comment]
Happy to give you more details. What do you need to know? I'm running on Mac OS X 10.11.3, unstable rust installed via homebrew (`brew install rust --head`). This was happening with the rust I compiled on Jan 2, so I recompiled it on 2016-02-07 and got the exact same results.

I don't understand the error, it appears to be a Diesel error.

Originally I was trying to get Diesel working for my own code but I kept getting the `Expected a struct or tuple struct for `#[insertable_into]`` error. I then downloaded this sample and tried it out as a sanity check and it failed the same way, so I reported the bug.

What version of rust is this known to work with?

**Comment by sgrif** [comment]
Any version later than `nightly-2016-01-16`. Sorry, not sure what else to tell you. I am unable to reproduce the problem, and many others have compiled this sample and the library just fine. It sounds like some kind of problem with your rust installation.

**Comment by caldwell** [comment]
In case anyone else runs into this, I switched from installing rust with [brew](http://brew.sh/) to installing with [rustup](https://static.rust-lang.org/rustup.sh) and I stopped getting the error. There must be something wrong with brew's install process.

**Comment by rattrayalex** [comment]
friendlier link: https://www.rustup.rs/

**Comment by rattrayalex** [comment]
`cargo run --bin show_posts` did not work for me until I installed `rustup` and ran `rustup default nightly`. 

Perhaps this could be in the early part of the documentation?

**Comment by rattrayalex** [comment]
I also found it helpful to add `source $HOME/.cargo/env` to my bash_profile; might also be nice to add to such a rust-beginner-friendly tutorial
