### ISSUE TITLE
Does not compile on nightly-2016-07-07

### ISSUE THREAD

**Issue by punmechanic** [sgrif/diesel_demo#7]
The guide for this demo specifies it will compile on 2016-07-07 nightly. However, after actually following the guide and trying to compile it using `rustup`:

```
$ rustup run nightly-2016-07-07 cargo build
```

I will get errors about `ast::SyntaxTree` being out of scope. This was corrected in `dotenv_macros` version `0.9.0`, but the guide continues to suggest `0.8.0`. 

Additionally, `diesel_codegen@0.7.0` has no `nightly` feature.

**Comment by punmechanic** [comment]
see https://github.com/slapresta/rust-dotenv/pull/44

**Comment by sgrif** [comment]
Thanks for the issue. This repo is more or less deprecated. The example code now lives on the diesel repo itself and I'm in the process of changing the guides to autogenerate from that code. Once that's done I'll be deleting this repo.
